version: "3.8"

services:
  app:  ## service name
    container_name: haha
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - "9999:8080"